# fly.toml file generated for notiffy on 2023-03-16T18:28:57-03:00

app = "notiffy"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[experimental]
  auto_rollback = true

[processes]
  app = ""
  cron = "cron -f"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  processes = ["sleep"]
  http_checks = []
  script_checks = []
  tcp_checks = []
