name: 000webhost

on:
  push:
    branches:
      - webhost

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code from notiffy/static
        uses: actions/checkout@v2

      - name: Install required packages
        uses: php-actions/composer@v6
        with:
          php_version: 8.0

      - name: Build environment variables file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: "./"
          file: ".env"
          content: |
            DB_HOST=${{ secrets.NOTIFFY_DB_HOSTNAME }}
            DB_NAME=${{ secrets.NOTIFFY_DB_NAME }}
            DB_USER=${{ secrets.NOTIFFY_DB_USERNAME }}
            DB_PASS=${{ secrets.NOTIFFY_DB_PASSWORD }}
            RECAPTCHA_CREDENTIALS='${{ secrets.NOTIFFY_RECAPTCHA_CREDENTIALS }}'
            RECAPTCHA_KEY=${{ secrets.NOTIFFY_RECAPTCHA_KEY }}
            SMTP_HOST=${{ secrets.NOTIFFY_SMTP_HOSTNAME }}
            SMTP_PORT=${{ secrets.NOTIFFY_SMTP_PORT }}
            SMTP_USER=${{ secrets.NOTIFFY_SMTP_USERNAME }}
            SMTP_PASS=${{ secrets.NOTIFFY_SMTP_PASSWORD }}

      - name: Upload project to host
        env:
          LFTP_SERVER: ${{ secrets.FTP_SERVER_DIR }}
          LFTP_HOST: ${{ secrets.FTP_HOSTNAME }}
          LFTP_USER: ${{ secrets.FTP_USERNAME }}
          LFTP_PASS: ${{ secrets.FTP_PASSWORD }}
          LFTP_EXCLUDE: "^.htaccess' '^.git' '.md' '^.ftpquota' 'LICENSE' 'VERSION' '^output.log' '^DOCKER_ENV' '^docker_tag' 'logs/' 'docs/' 'doc/' 'tmp/'"
          LFTP_ARGS: "--no-empty-dirs --delete-excluded --parallel=10 --no-perms --verbose --reverse --delete"
          LFTP_LOCAL: "./"
          LFTP_FLAGS: "'ftp:use-mode-z true' 'ftp:mode-z-level 9' 'net:timeout 30'"
          LFTP_COMMAND: "$FLAGS mirror $LFTP_ARGS $EXCLUDE $LFTP_LOCAL $LFTP_FLAGS; exit 0"
        run: |
          for excluded in $LFTP_EXCLUDE do EXCLUDE="$EXCLUDE --exclude $excluded" done
          for flag in $LFTP_FLAGS do FLAGS="$FLAGS set $flag;" done
          lftp $LFTP_HOST -u $LFTP_USER,$LFTP_PASS -e "$LFTP_COMMAND"