name: 000webhost

on:
  push:
    branches:
      - webhost

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code from notiffy/static
        uses: actions/checkout@v2

      - name: Install required packages
        uses: php-actions/composer@v6
        with:
          php_version: 8.0

      - name: Build environment variables file
        uses: 1arp/create-a-file-action@0.2
        with:
          path: "./"
          file: ".env"
          content: |
            DB_HOST=${{ secrets.NOTIFFY_DB_HOSTNAME }}
            DB_NAME=${{ secrets.NOTIFFY_DB_NAME }}
            DB_USER=${{ secrets.NOTIFFY_DB_USERNAME }}
            DB_PASS=${{ secrets.NOTIFFY_DB_PASSWORD }}
            RECAPTCHA_CREDENTIALS='${{ secrets.NOTIFFY_RECAPTCHA_CREDENTIALS }}'
            RECAPTCHA_KEY=${{ secrets.NOTIFFY_RECAPTCHA_KEY }}
            SMTP_HOST=${{ secrets.NOTIFFY_SMTP_HOSTNAME }}
            SMTP_PORT=${{ secrets.NOTIFFY_SMTP_PORT }}
            SMTP_USER=${{ secrets.NOTIFFY_SMTP_USERNAME }}
            SMTP_PASS=${{ secrets.NOTIFFY_SMTP_PASSWORD }}

      - name: Upload project to host
        uses: .github/actions/deploy-using-lftp
        with:
          lftp_host: ${{ secrets.FTP_HOSTNAME }}
          lftp_user: ${{ secrets.FTP_USERNAME }}
          lftp_pass: ${{ secrets.FTP_PASSWORD }}
          lftp_exclude: "'^.htaccess' '^.git' '.md' '^.ftpquota' 'LICENSE' 'VERSION' '^output.log' '^DOCKER_ENV' '^docker_tag' 'logs/' 'docs/' 'doc/' 'tmp/'"
          lftp_args: "--no-empty-dirs --delete-excluded --parallel=10 --no-perms --verbose --reverse --delete"
          lftp_flags: "'ftp:use-mode-z true' 'ftp:mode-z-level 9' 'net:timeout 30'"
